In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape, arr_2d.shape

((3,), (3, 3))

In [ ]:
x = np.array([1,2,3])
c = 5

print(f'더하기: {x + c}')
print(f'빼기: {x - c}')
print(f'곱하기: {x * c}')
print(f'나누기: {x / c}')

더하기: [6 7 8]
빼기: [-4 -3 -2]
곱하기: [ 5 10 15]
나누기: [0.2 0.4 0.6]


In [ ]:
y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print(f'더하기: {y + z}')
print(f'빼기: {y-z}')
print(f'곱하기: {y*z}')
print(f'나누기: {y/z}')

더하기: [ 3 12 25]
빼기: [ -1  -6 -15]
곱하기: [  2  27 100]
나누기: [0.5        0.33333333 0.25      ]


In [ ]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(W[0,0]) #1행 1열
print(W[2,3]) #3행 4열

1
12


In [ ]:
W = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(W[0:2,1:3]) # 행은 1~2행, 열은 2~3열

[[2 3]
 [6 7]]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
x = np.array([0, 1, 0])
x = x[:,None]
print(a + x)

[0 1 0]
[[1 2 3]
 [5 6 7]
 [7 8 9]]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([0, 1, -1])
print(a * y)

[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]


In [ ]:
t = np.array([[1], [2], [3]])
u = np.array([2, 0, -2])

print(t + u)

[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


In [ ]:
np.zeros(3)[:,None]

array([[0.],
       [0.],
       [0.]])

In [ ]:
np.diag((2, 4))

array([[2, 0],
       [0, 4]])

In [ ]:
np.eye(2, dtype=int)

array([[1, 0],
       [0, 1]])

In [ ]:
a = np.array([[1, 4], [2, 3]])
b = np.array([[7, 9], [0, 6]])
print(a.dot(b))
print(a @ b)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


In [ ]:
arr = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
print(arr.trace())
print(np.eye(2,dtype=int).trace())

15
2


In [ ]:
arr = np.array([[2, 3], [1, 6]])
print(arr)
print(np.linalg.det(arr))

[[2 3]
 [1 6]]
9.000000000000002


In [ ]:
mat = np.array([[1, 4], [2, 3]])
print(mat)
mat_inv = np.linalg.inv(mat)
print(mat_inv)
print(mat @ mat_inv)

[[1 4]
 [2 3]]
[[-0.6  0.8]
 [ 0.4 -0.2]]
[[ 1.00000000e+00  0.00000000e+00]
 [-1.11022302e-16  1.00000000e+00]]


In [ ]:
mat = np.array([[2, 0 ,-2], [1, 1, -2], [0, 0, 1]])
print(mat)
print(np.linalg.eig(mat))

[[ 2  0 -2]
 [ 1  1 -2]
 [ 0  0  1]]
(array([1., 2., 1.]), array([[0.        , 0.70710678, 0.89442719],
       [1.        , 0.70710678, 0.        ],
       [0.        , 0.        , 0.4472136 ]]))


In [ ]:
a = np.arange(4)

def get_L2_norm(arr):
  return np.linalg.norm(arr, 2)

print(get_L2_norm(a))

3.7416573867739413


In [ ]:
arr = np.array([[2, 3], [1, 6]])
arr2 = np.array([[3, 2], [3, 2]])
def is_singular(arr):
  if np.linalg.det(arr) == 0:
    return True
  return False

print(is_singular(arr))
print(is_singular(arr2))

False
True
