* 랜덤 포레스트(Random Forest) 모델은 결정 트리의 단점인 오버피팅 문제를 완화시켜주는 발전된 형태의 트리 모델이다. 랜덤으로 생성된 무수히 많은 트리를 이용하여 예측을 하기 때문에 랜덤 포레스트라고 부른다. 이렇게 여러 모델을 활용하여 하나의 모델을 이루는 기법을 앙상블이라 부른다.

* 장점
    * 결정 트리와 마찬가지로, 아웃라이어에 거의 영향을 받지 않는다.
    * 선형, 비선형 데이터에 상관없이 잘 작동한다.
* 단점
    * 학습 속도가 상대적으로 느린편이다.
    * 수많은 트리를 동원하기 때문에 모델에 대한 해석이 어렵다.

## 9.1 문제 정의 : 한눈에 보는 예측 목표

* 미션 : 중고차 판매 이력 데이터셋을 이용해 중고차 가격을 예측하라
* 알고리즘: 랜덤 포레스트
* 문제 유형: 회귀
* 평가지표: RSME


## 9.2 라이브러리 및 데이터 불러오기, 데이터 확인하기

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

file_url = 'https://media.githubusercontent.com/media/musthave-ML10/data_source/main/car.csv'
data = pd.read_csv(file_url)

In [2]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner     mileage   engine   max_power  \
0  Individual       Manual   First Owner   23.4 kmpl  1248 CC      74 bhp   
1  Individual       Manual  Second Owner  21.14 kmpl  1498 CC  103.52 bhp   
2  Individual       Manual   Third Owner   17.7 kmpl  1497 CC      78 bhp   
3  Individual       Manual   First Owner   23.0 kmpl  1396 CC      90 bhp   
4  Individual       Manual   First Owner   16.1 kmpl  1298 CC    88.2 bhp   

                     torque  seats  
0            190Nm@ 2000rpm    5.0  
1       250Nm@ 1500-2500rpm    5.0  
2     12.7@ 2,700(kgm@ rpm)    5.0  
3  22.4 kgm at 1750-2750rpm    5.0  
4     11.5@ 4,500(kgm@ rpm)    5.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   name           8128 non-null   object 
 1   year           8128 non-null   int64  
 2   selling_price  8128 non-null   int64  
 3   km_driven      8128 non-null   int64  
 4   fuel           8128 non-null   object 
 5   seller_type    8128 non-null   object 
 6   transmission   8128 non-null   object 
 7   owner          8128 non-null   object 
 8   mileage        7907 non-null   object 
 9   engine         7907 non-null   object 
 10  max_power      7913 non-null   object 
 11  torque         7906 non-null   object 
 12  seats          7907 non-null   float64
dtypes: float64(1), int64(3), object(9)
memory usage: 825.6+ KB


In [4]:
round(data.describe(), 2)

year  selling_price   km_driven    seats
count  8128.00        8128.00     8128.00  7907.00
mean   2013.80      638271.81    69819.51     5.42
std       4.04      806253.40    56550.55     0.96
min    1983.00       29999.00        1.00     2.00
25%    2011.00      254999.00    35000.00     5.00
50%    2015.00      450000.00    60000.00     5.00
75%    2017.00      675000.00    98000.00     5.00
max    2020.00    10000000.00  2360457.00    14.00

## 9.3 전처리: 텍스트 데이터

### 9.3.1 engine 변수 전처리하기

In [5]:
data['engine'].str.split(expand=True)

0   1
0     1248  CC
1     1498  CC
2     1497  CC
3     1396  CC
4     1298  CC
...    ...  ..
8123  1197  CC
8124  1493  CC
8125  1248  CC
8126  1396  CC
8127  1396  CC

[8128 rows x 2 columns]

In [6]:
data[['engine', 'engine_unit']] = data['engine'].str.split(expand=True)

In [7]:
data['engine'].head()

0    1248
1    1498
2    1497
3    1396
4    1298
Name: engine, dtype: object

In [8]:
data['engine'] = data['engine'].astype('float32')

In [9]:
data['engine'].head()

0    1248.0
1    1498.0
2    1497.0
3    1396.0
4    1298.0
Name: engine, dtype: float32

In [10]:
data['engine_unit'].unique()

array(['CC', nan], dtype=object)

In [11]:
data.drop('engine_unit', axis=1, inplace=True)

### 9.3.2 max_power 변수 전처리하기

In [12]:
data['max_power'].str.split(expand=True)

0    1
0         74  bhp
1     103.52  bhp
2         78  bhp
3         90  bhp
4       88.2  bhp
...      ...  ...
8123   82.85  bhp
8124     110  bhp
8125    73.9  bhp
8126      70  bhp
8127      70  bhp

[8128 rows x 2 columns]

In [13]:
data[['max_power', 'max_power_unit']] = data['max_power'].str.split(expand=True)

In [14]:
data['max_power'].head()

0        74
1    103.52
2        78
3        90
4      88.2
Name: max_power, dtype: object

In [15]:
data['max_power'] = data['max_power'].astype('float32')

ValueError: could not convert string to float: 'bhp'

In [16]:
data[data['max_power'] == 'bhp']

name  year  selling_price  km_driven fuel seller_type  \
4933  Maruti Omni CNG  2000          80000     100000  CNG  Individual   

     transmission         owner     mileage  engine max_power torque  seats  \
4933       Manual  Second Owner  10.9 km/kg   796.0       bhp    NaN    8.0   

     max_power_unit  
4933           None

In [17]:
def isFloat(value):
    try:
        num = float(value)
        return num
    except ValueError:
        return np.NaN

In [18]:
data['max_power'] = data['max_power'].apply(isFloat)

In [19]:
data['max_power_unit'].unique()

array(['bhp', nan, None], dtype=object)

In [20]:
data.drop('max_power_unit', axis=1, inplace=True)

### 9.3.3 mileage 변수 전처리하기

In [21]:
data[['mileage', 'mileage_unit']] = data['mileage'].str.split(expand=True)

In [22]:
data['mileage'] = data['mileage'].astype('float32')

In [23]:
data['mileage_unit'].unique()

array(['kmpl', 'km/kg', nan], dtype=object)

In [24]:
data['fuel'].unique()

array(['Diesel', 'Petrol', 'LPG', 'CNG'], dtype=object)

In [25]:
def mile(x):
    if x['fuel'] == 'Petrol':
        return x['mileage'] / 80.43
    elif x['fuel'] == 'Diesel':
        return x['mileage'] / 73.56
    elif x['fuel'] == 'LPG':
        return x['mileage'] / 40.85
    else:
        return x['mileage'] / 44.23

In [26]:
data['mileage'] = data.apply(mile, axis=1)

In [27]:
data.drop('mileage_unit', axis=1, inplace=True)

### 9.3.4 torque 변수 전처리하기

In [28]:
data['torque'].head()

0              190Nm@ 2000rpm
1         250Nm@ 1500-2500rpm
2       12.7@ 2,700(kgm@ rpm)
3    22.4 kgm at 1750-2750rpm
4       11.5@ 4,500(kgm@ rpm)
Name: torque, dtype: object

In [29]:
data['torque'] = data['torque'].str.upper()

In [30]:
def torque_unit(x):
    if 'NM' in str(x):
        return 'Nm'
    elif 'KGM' in str(x):
        return 'kgm'

In [31]:
data['torque_unit'] = data['torque'].apply(torque_unit)

In [32]:
data['torque_unit'].unique()

array(['Nm', 'kgm', None], dtype=object)

In [33]:
data[data['torque_unit'].isna()]['torque'].unique()

array([nan, '250@ 1250-5000RPM', '510@ 1600-2400', '110(11.2)@ 4800',
       '210 / 1900'], dtype=object)

In [34]:
data['torque_unit'].fillna('Nm', inplace=True)

In [35]:
string_example = '12.7@ 2,700(KGM@ RPM)'

In [36]:
for i, j in enumerate(string_example):
    print(i, '번째 테스트', j)

0 번째 테스트 1
1 번째 테스트 2
2 번째 테스트 .
3 번째 테스트 7
4 번째 테스트 @
5 번째 테스트  
6 번째 테스트 2
7 번째 테스트 ,
8 번째 테스트 7
9 번째 테스트 0
10 번째 테스트 0
11 번째 테스트 (
12 번째 테스트 K
13 번째 테스트 G
14 번째 테스트 M
15 번째 테스트 @
16 번째 테스트  
17 번째 테스트 R
18 번째 테스트 P
19 번째 테스트 M
20 번째 테스트 )


In [37]:
for i,j in enumerate(string_example):
    if j not in '0123456789.':
        cut = i
        break

In [38]:
def split_num(x):
    x = str(x)
    for i,j in enumerate(x):
        if j not in '0123456789.':
            cut = i
            break
    return x[:cut]

In [39]:
data['torque'] = data['torque'].apply(split_num)

In [40]:
data['torque']

0         190
1         250
2        12.7
3        22.4
4        11.5
        ...  
8123    113.7
8124       24
8125      190
8126      140
8127      140
Name: torque, Length: 8128, dtype: object

In [41]:
data['torque'] = data['torque'].astype('float64')

ValueError: could not convert string to float: ''

In [42]:
data['torque'] = data['torque'].replace('', np.NaN)

In [43]:
data['torque'] = data['torque'].astype('float64')

In [44]:
data['torque'].head()

0    190.0
1    250.0
2     12.7
3     22.4
4     11.5
Name: torque, dtype: float64

In [45]:
def torque_trans(x):
    if x['torque_unit'] == 'kgm':
        return x['torque'] * 9.8066
    else:
        return x['torque']

In [46]:
data['torque'] = data.apply(torque_trans, axis=1)

In [47]:
data.drop('torque_unit', axis=1, inplace=True)

In [48]:
data.head()

name  year  selling_price  km_driven    fuel  \
0        Maruti Swift Dzire VDI  2014         450000     145500  Diesel   
1  Skoda Rapid 1.5 TDI Ambition  2014         370000     120000  Diesel   
2      Honda City 2017-2020 EXi  2006         158000     140000  Petrol   
3     Hyundai i20 Sportz Diesel  2010         225000     127000  Diesel   
4        Maruti Swift VXI BSIII  2007         130000     120000  Petrol   

  seller_type transmission         owner   mileage  engine  max_power  \
0  Individual       Manual   First Owner  0.318108  1248.0      74.00   
1  Individual       Manual  Second Owner  0.287384  1498.0     103.52   
2  Individual       Manual   Third Owner  0.220067  1497.0      78.00   
3  Individual       Manual   First Owner  0.312670  1396.0      90.00   
4  Individual       Manual   First Owner  0.200174  1298.0      88.20   

      torque  seats  
0  190.00000    5.0  
1  250.00000    5.0  
2  124.54382    5.0  
3  219.66784    5.0  
4  112.77590    5.0

### 9.3.5 name 변수 전처리하기

In [49]:
data['name'] = data['name'].str.split(expand=True)[0]

In [50]:
data['name'].unique()

array(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
       'Mahindra', 'Tata', 'Chevrolet', 'Fiat', 'Datsun', 'Jeep',
       'Mercedes-Benz', 'Mitsubishi', 'Audi', 'Volkswagen', 'BMW',
       'Nissan', 'Lexus', 'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo',
       'Kia', 'Force', 'Ambassador', 'Ashok', 'Isuzu', 'Opel', 'Peugeot'],
      dtype=object)

In [51]:
data['name'] = data['name'].replace('Land', 'Land Rover')

## 9.4 전처리 : 결측치 처리와 더미 변수 변환

In [52]:
data.isna().mean()

name             0.000000
year             0.000000
selling_price    0.000000
km_driven        0.000000
fuel             0.000000
seller_type      0.000000
transmission     0.000000
owner            0.000000
mileage          0.027190
engine           0.027190
max_power        0.026575
torque           0.027313
seats            0.027190
dtype: float64

In [53]:
# 결측치 비율이 높지 않으므로 과감히 삭제
data.dropna(inplace=True)
len(data)

7906

In [54]:
# 더미 변수 변환
data = pd.get_dummies(data, columns=['name', 'fuel', 'seller_type', 'transmission', 'owner'], drop_first=True)

In [55]:
data.head()

year  selling_price  km_driven   mileage  engine  max_power     torque  \
0  2014         450000     145500  0.318108  1248.0      74.00  190.00000   
1  2014         370000     120000  0.287384  1498.0     103.52  250.00000   
2  2006         158000     140000  0.220067  1497.0      78.00  124.54382   
3  2010         225000     127000  0.312670  1396.0      90.00  219.66784   
4  2007         130000     120000  0.200174  1298.0      88.20  112.77590   

   seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0    5.0           0          0  ...            1         0            0   
1    5.0           0          0  ...            1         0            0   
2    5.0           0          0  ...            0         0            1   
3    5.0           0          0  ...            1         0            0   
4    5.0           0          0  ...            0         0            1   

   seller_type_Individual  seller_type_Trustmark Dealer  transmission_Manual  \
0                       1                             0                    1   
1                       1                             0                    1   
2                       1                             0                    1   
3                       1                             0                    1   
4                       1                             0                    1   

   owner_Fourth & Above Owner  owner_Second Owner  owner_Test Drive Car  \
0                           0                   0                     0   
1                           0                   1                     0   
2                           0                   0                     0   
3                           0                   0                     0   
4                           0                   0                     0   

   owner_Third Owner  
0                  0  
1                  0  
2                  1  
3                  0  
4                  0  

[5 rows x 48 columns]

## 9.5 모델링 및 평가하기

In [56]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data.drop('selling_price', axis=1), data['selling_price'], test_size=0.2, random_state=100)

In [57]:
from sklearn.ensemble import RandomForestRegressor

In [58]:
model = RandomForestRegressor(random_state=100)

In [59]:
model.fit(X_train, y_train)
train_pred = model.predict(X_train)
test_pred = model.predict(X_test)


In [60]:
from sklearn.metrics import mean_squared_error
print(f'train_rsme: {mean_squared_error(y_train, train_pred) ** 0.5} test_rsme: {mean_squared_error(y_test, test_pred) ** 0.5}')

train_rsme: 53531.41548125947 test_rsme: 131855.18391308116


## 9.6 이해하기 : K-폴드 교차검증

* 교차검증(cross validate)의 목적은 모델의 예측력을 더 안정적으로 평가하기 위함이다.

In [61]:
from sklearn.model_selection import KFold

In [63]:
data

year  selling_price  km_driven   mileage  engine  max_power     torque  \
0     2014         450000     145500  0.318108  1248.0      74.00  190.00000   
1     2014         370000     120000  0.287384  1498.0     103.52  250.00000   
2     2006         158000     140000  0.220067  1497.0      78.00  124.54382   
3     2010         225000     127000  0.312670  1396.0      90.00  219.66784   
4     2007         130000     120000  0.200174  1298.0      88.20  112.77590   
...    ...            ...        ...       ...     ...        ...        ...   
8123  2013         320000     110000  0.230014  1197.0      82.85  113.70000   
8124  2007         135000     119000  0.228385  1493.0     110.00  235.35840   
8125  2009         382000     120000  0.262371  1248.0      73.90  190.00000   
8126  2013         290000      25000  0.320419  1396.0      70.00  140.00000   
8127  2013         290000      25000  0.320419  1396.0      70.00  140.00000   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0       5.0           0          0  ...            1         0            0   
1       5.0           0          0  ...            1         0            0   
2       5.0           0          0  ...            0         0            1   
3       5.0           0          0  ...            1         0            0   
4       5.0           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
8123    5.0           0          0  ...            0         0            1   
8124    5.0           0          0  ...            1         0            0   
8125    5.0           0          0  ...            1         0            0   
8126    5.0           0          0  ...            1         0            0   
8127    5.0           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
8123                       1                             0   
8124                       1                             0   
8125                       1                             0   
8126                       1                             0   
8127                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
8123                    1                           0                   0   
8124                    1                           1                   0   
8125                    1                           0                   0   
8126                    1                           0                   0   
8127                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
8123                     0                  0  
8124                     0                

In [64]:
data.reset_index(drop=True, inplace=True)

In [65]:
data

year  selling_price  km_driven   mileage  engine  max_power     torque  \
0     2014         450000     145500  0.318108  1248.0      74.00  190.00000   
1     2014         370000     120000  0.287384  1498.0     103.52  250.00000   
2     2006         158000     140000  0.220067  1497.0      78.00  124.54382   
3     2010         225000     127000  0.312670  1396.0      90.00  219.66784   
4     2007         130000     120000  0.200174  1298.0      88.20  112.77590   
...    ...            ...        ...       ...     ...        ...        ...   
7901  2013         320000     110000  0.230014  1197.0      82.85  113.70000   
7902  2007         135000     119000  0.228385  1493.0     110.00  235.35840   
7903  2009         382000     120000  0.262371  1248.0      73.90  190.00000   
7904  2013         290000      25000  0.320419  1396.0      70.00  140.00000   
7905  2013         290000      25000  0.320419  1396.0      70.00  140.00000   

      seats  name_Ashok  name_Audi  ...  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0       5.0           0          0  ...            1         0            0   
1       5.0           0          0  ...            1         0            0   
2       5.0           0          0  ...            0         0            1   
3       5.0           0          0  ...            1         0            0   
4       5.0           0          0  ...            0         0            1   
...     ...         ...        ...  ...          ...       ...          ...   
7901    5.0           0          0  ...            0         0            1   
7902    5.0           0          0  ...            1         0            0   
7903    5.0           0          0  ...            1         0            0   
7904    5.0           0          0  ...            1         0            0   
7905    5.0           0          0  ...            1         0            0   

      seller_type_Individual  seller_type_Trustmark Dealer  \
0                          1                             0   
1                          1                             0   
2                          1                             0   
3                          1                             0   
4                          1                             0   
...                      ...                           ...   
7901                       1                             0   
7902                       1                             0   
7903                       1                             0   
7904                       1                             0   
7905                       1                             0   

      transmission_Manual  owner_Fourth & Above Owner  owner_Second Owner  \
0                       1                           0                   0   
1                       1                           0                   1   
2                       1                           0                   0   
3                       1                           0                   0   
4                       1                           0                   0   
...                   ...                         ...                 ...   
7901                    1                           0                   0   
7902                    1                           1                   0   
7903                    1                           0                   0   
7904                    1                           0                   0   
7905                    1                           0                   0   

      owner_Test Drive Car  owner_Third Owner  
0                        0                  0  
1                        0                  0  
2                        0                  1  
3                        0                  0  
4                        0                  0  
...                    ...                ...  
7901                     0                  0  
7902                     0                

In [66]:
kf = KFold(n_splits=5)

In [67]:
X = data.drop('selling_price', axis=1)
y = data['selling_price']

In [68]:
for i, j in kf.split(X):
    print(i, j)

[1582 1583 1584 ... 7903 7904 7905] [   0    1    2 ... 1579 1580 1581]
[   0    1    2 ... 7903 7904 7905] [1582 1583 1584 ... 3160 3161 3162]
[   0    1    2 ... 7903 7904 7905] [3163 3164 3165 ... 4741 4742 4743]
[   0    1    2 ... 7903 7904 7905] [4744 4745 4746 ... 6322 6323 6324]
[   0    1    2 ... 6322 6323 6324] [6325 6326 6327 ... 7903 7904 7905]


In [70]:
train_rmse_total = []
test_rmse_total = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.loc[train_index], X.loc[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    model = RandomForestRegressor(random_state=100)
    model.fit(X_train, y_train)
    train_pred = model.predict(X_train)
    test_pred = model.predict(X_test)

    train_rmse = mean_squared_error(y_train, train_pred) ** 0.5
    test_rmse = mean_squared_error(y_test, test_pred) ** 0.5

    train_rmse_total.append(train_rmse)
    test_rmse_total.append(test_rmse)

In [71]:
train_rmse_total

[50825.5556350298,
 58854.04054344074,
 57904.19615940739,
 56218.23740006373,
 58967.150857632456]

In [72]:
print(f'train_rmse: {sum(train_rmse_total)/ 5} test_rmse: {sum(test_rmse_total)/5}')

train_rmse: 56553.836119114814 test_rmse: 142936.58918244042


## 9.7 이해하기 : 랜덤 포레스트