In [1]:
%matplotlib inline

In [2]:
from __future__ import print_function
import torch

In [3]:
torch.__version__

'2.0.0+cu118'

In [4]:
# 초기화되지 않은 5x3 행렬 생성
x = torch.empty(5, 3)
print(x)

tensor([[4.2193e-08, 1.0781e-08, 2.1707e-18],
        [4.5447e+30, 7.0062e+22, 2.1715e-18],
        [4.5447e+30, 7.0062e+22, 2.1707e-18],
        [1.9284e+31, 3.2314e-18, 7.4767e+20],
        [6.6657e-10, 1.0027e-11, 2.5935e-09]])


In [5]:
x = torch.randn(5, 3) # normal distribution에서 생성
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[-0.6904,  2.0403,  2.1867],
        [-1.0009, -1.5196, -0.2559],
        [ 1.0840,  0.3173, -0.7619],
        [-0.4850, -0.5771,  0.3900],
        [ 0.4547, -0.4450, -1.0569]])
tensor([[0.8725, 0.3021, 0.6527],
        [0.6728, 0.6136, 0.8231],
        [0.3023, 0.0694, 0.0631],
        [0.0266, 0.6160, 0.0149],
        [0.3209, 0.5182, 0.8789]])


In [6]:
# dtype이 long이고 0으로 채워진 행렬을 생성.
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)

In [10]:
print(x)

tensor([[-0.1666,  1.7148,  0.2463],
        [-1.6418,  0.6305,  0.3013],
        [-0.3545, -0.1393,  0.0510],
        [-0.0360,  1.9027,  0.3356],
        [-0.3992, -0.8955,  0.3509]])


In [11]:
print(x.dtype)

torch.float32


In [12]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [13]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-0.1666,  1.7148,  0.2463],
        [-1.6418,  0.6305,  0.3013],
        [-0.3545, -0.1393,  0.0510],
        [-0.0360,  1.9027,  0.3356],
        [-0.3992, -0.8955,  0.3509]])
tensor([[0.3524, 0.1740, 0.6961],
        [0.9466, 0.4499, 0.8839],
        [0.0397, 0.0315, 0.0437],
        [0.4536, 0.8321, 0.3937],
        [0.8804, 0.9897, 0.0273]])
tensor([[ 0.1858,  1.8888,  0.9424],
        [-0.6952,  1.0804,  1.1852],
        [-0.3149, -0.1078,  0.0947],
        [ 0.4176,  2.7348,  0.7293],
        [ 0.4812,  0.0942,  0.3782]])


In [14]:
print(torch.add(x, y))

tensor([[ 0.1858,  1.8888,  0.9424],
        [-0.6952,  1.0804,  1.1852],
        [-0.3149, -0.1078,  0.0947],
        [ 0.4176,  2.7348,  0.7293],
        [ 0.4812,  0.0942,  0.3782]])


In [15]:
result = torch.empty(5, 3)
print(result)
torch.add(x, y, out=result)
print(result)

tensor([[ 3.5918e-34,  0.0000e+00,  4.1840e-35],
        [ 0.0000e+00, -3.1502e+21,  4.5879e-41],
        [ 1.4013e-45,  0.0000e+00,  2.1019e-44],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[ 0.1858,  1.8888,  0.9424],
        [-0.6952,  1.0804,  1.1852],
        [-0.3149, -0.1078,  0.0947],
        [ 0.4176,  2.7348,  0.7293],
        [ 0.4812,  0.0942,  0.3782]])


In [16]:
print(y)
y.add_(x) #inplace 방식, 새로운 텐서를 생성하는게 아니라 기존 y에 덮어쓴다?
print(y)

tensor([[0.3524, 0.1740, 0.6961],
        [0.9466, 0.4499, 0.8839],
        [0.0397, 0.0315, 0.0437],
        [0.4536, 0.8321, 0.3937],
        [0.8804, 0.9897, 0.0273]])
tensor([[ 0.1858,  1.8888,  0.9424],
        [-0.6952,  1.0804,  1.1852],
        [-0.3149, -0.1078,  0.0947],
        [ 0.4176,  2.7348,  0.7293],
        [ 0.4812,  0.0942,  0.3782]])


In [17]:
print(x)
print(x[:, 1])

tensor([[-0.1666,  1.7148,  0.2463],
        [-1.6418,  0.6305,  0.3013],
        [-0.3545, -0.1393,  0.0510],
        [-0.0360,  1.9027,  0.3356],
        [-0.3992, -0.8955,  0.3509]])
tensor([ 1.7148,  0.6305, -0.1393,  1.9027, -0.8955])


In [18]:
x = torch.randn(4, 4)
print(x)
y = x.view(-1)
z = y.view(-1, 2)
q = x.view(-1, 1)
print(y)
print(z)
print(q)
print(y.shape, z.shape, q.shape)

tensor([[ 0.8570,  0.0647, -0.8299,  0.6369],
        [-0.3652, -1.4014, -0.4168, -0.0702],
        [-0.0054, -0.1026,  0.2425, -1.3273],
        [ 0.6861,  1.3469,  1.2109,  0.4528]])
tensor([ 0.8570,  0.0647, -0.8299,  0.6369, -0.3652, -1.4014, -0.4168, -0.0702,
        -0.0054, -0.1026,  0.2425, -1.3273,  0.6861,  1.3469,  1.2109,  0.4528])
tensor([[ 0.8570,  0.0647],
        [-0.8299,  0.6369],
        [-0.3652, -1.4014],
        [-0.4168, -0.0702],
        [-0.0054, -0.1026],
        [ 0.2425, -1.3273],
        [ 0.6861,  1.3469],
        [ 1.2109,  0.4528]])
tensor([[ 0.8570],
        [ 0.0647],
        [-0.8299],
        [ 0.6369],
        [-0.3652],
        [-1.4014],
        [-0.4168],
        [-0.0702],
        [-0.0054],
        [-0.1026],
        [ 0.2425],
        [-1.3273],
        [ 0.6861],
        [ 1.3469],
        [ 1.2109],
        [ 0.4528]])
torch.Size([16]) torch.Size([8, 2]) torch.Size([16, 1])


In [19]:
# 텐서에 값이 1개밖에 없을때 가져오기
x = torch.randn(1)
print(x)
print(type(x), print(x.item()))
print(type(x.item()))

tensor([0.2782])
0.2782163918018341
<class 'torch.Tensor'> None
<class 'float'>


In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [23]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [24]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [25]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [26]:
from torch.cuda import is_available
x = torch.randn(4, 4)
if torch.cuda.is_available():
  device = "cuda:0"
  y = torch.ones_like(x, device=device)
  print(y)

  x = x.to(device)
  z = x + y
  print(z)
  print(z.to("cpu", torch.double))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[-0.3607,  0.4543,  1.0969,  0.2680],
        [-0.2994, -0.2952,  0.3038,  1.0042],
        [ 0.0150,  1.8328,  0.1844,  2.0240],
        [-0.4421,  1.3867,  1.3950, -0.3633]], device='cuda:0')
tensor([[-0.3607,  0.4543,  1.0969,  0.2680],
        [-0.2994, -0.2952,  0.3038,  1.0042],
        [ 0.0150,  1.8328,  0.1844,  2.0240],
        [-0.4421,  1.3867,  1.3950, -0.3633]], dtype=torch.float64)


In [27]:
x = x.cuda()

In [28]:
print(x)

tensor([[-1.3607, -0.5457,  0.0969, -0.7320],
        [-1.2994, -1.2952, -0.6962,  0.0042],
        [-0.9850,  0.8328, -0.8156,  1.0240],
        [-1.4421,  0.3867,  0.3950, -1.3633]], device='cuda:0')


---

In [29]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [30]:
my_variable = tf.Variable(tf.zeros([1, 2, 3]))
my_variable

<tf.Variable 'Variable:0' shape=(1, 2, 3) dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [31]:
v = tf.Variable(0.0)
print(v)
w = v + 1
print(w)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=0.0>
tf.Tensor(1.0, shape=(), dtype=float32)


In [32]:
a = tf.Variable(0.0)
a.assign_add(1)
a.read_value()

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [33]:
mammal = tf.Variable("코끼리", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.14159265359, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

print(mammal)
print(ignition)
print(floating)
print(its_complicated)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'\xec\xbd\x94\xeb\x81\xbc\xeb\xa6\xac'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=451>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.1415927>
<tf.Variable 'Variable:0' shape=() dtype=complex128, numpy=(12.3-4.85j)>


In [34]:
mystr = tf.Variable(["안녕하세요"], tf.string)
cool_numbers  = tf.Variable([3.14159, 2.71828], tf.float32)
first_primes = tf.Variable([2, 3, 5, 7, 11], tf.int32)
its_very_complicated = tf.Variable([12.3 - 4.85j, 7.5 - 6.23j], tf.complex64)

print(mystr)
print(cool_numbers)
print(first_primes)
print(its_very_complicated)
tf.rank(mystr)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=
array([b'\xec\x95\x88\xeb\x85\x95\xed\x95\x98\xec\x84\xb8\xec\x9a\x94'],
      dtype=object)>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3.14159, 2.71828], dtype=float32)>
<tf.Variable 'Variable:0' shape=(5,) dtype=int32, numpy=array([ 2,  3,  5,  7, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=complex128, numpy=array([12.3-4.85j,  7.5-6.23j])>


<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [35]:
mymat = tf.Variable([[7],[11]], tf.int16)
myxor = tf.Variable([[False, True],[True, False]], tf.bool)
linear_squares = tf.Variable([[4], [9], [16], [25]], tf.int32)
squarish_squares = tf.Variable([ [4, 9], [16, 25] ], tf.int32)

#tf.rank : 객체의 랭크 구하기 
rank_of_squares = tf.rank(squarish_squares)
mymatC = tf.Variable([[7],[11]], tf.int32)

print(mymat)
print(rank_of_squares)

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[ 7],
       [11]], dtype=int32)>
tf.Tensor(2, shape=(), dtype=int32)


In [36]:
my_image = tf.zeros([10, 299, 299, 3]) # 배치 x 높이 x 너비 x 색상

In [37]:
r = tf.rank(my_image)
print(r)

tf.Tensor(4, shape=(), dtype=int32)


In [39]:
rank_three_tensor = tf.ones([3, 4, 5])
print(rank_three_tensor)
matrix = tf.reshape(rank_three_tensor, [6, 10])
print(matrix.shape)
matrixB = tf.reshape(matrix, [3, -1])
print(matrixB.shape)

matrixAlt = tf.reshape(matrixB, [4, 3, -1])
print(matrixAlt.shape)

# yet_another = tf.reshape(matrixAlt, [13, 2, -1])

tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)
(6, 10)
(3, 20)
(4, 3, 5)
